"""create initial tables

Revision ID: ba50d4141bdc
Revises: 
Create Date: 2026-03-16 17:44:30.761797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba50d4141bdc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composite_scores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('bad_day_score', sa.Float(), nullable=False),
    sa.Column('convergence_flag', sa.Boolean(), nullable=False),
    sa.Column('signal_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_composite_scores_country_code'), 'composite_scores', ['country_code'], unique=False)
    op.create_index(op.f('ix_composite_scores_date'), 'composite_scores', ['date'], unique=False)
    op.create_table('normalised_scores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('signal_type', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalised_scores_country_code'), 'normalised_scores', ['country_code'], unique=False)
    op.create_index(op.f('ix_normalised_scores_date'), 'normalised_scores', ['date'], unique=False)
    op.create_table('raw_signals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal_type', sa.String(length=32), nullable=False),
    sa.Column('raw_value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_signals_country_code'), 'raw_signals', ['country_code'], unique=False)
    op.create_index(op.f('ix_raw_signals_timestamp'), 'raw_signals', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_signals_timestamp'), table_name='raw_signals')
    op.drop_index(op.f('ix_raw_signals_country_code'), table_name='raw_signals')
    op.drop_table('raw_signals')
    op.drop_index(op.f('ix_normalised_scores_date'), table_name='normalised_scores')
    op.drop_index(op.f('ix_normalised_scores_country_code'), table_name='normalised_scores')
    op.drop_table('normalised_scores')
    op.drop_index(op.f('ix_composite_scores_date'), table_name='composite_scores')
    op.drop_index(op.f('ix_composite_scores_country_code'), table_name='composite_scores')
    op.drop_table('composite_scores')
    # ### end Alembic commands ###
